services:
  - type: web
    name: virtual-india-ai
    env: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn internship_project.wsgi:application

